version: '3'

networks:
  condingexam:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: condingexam_nginx
    ports:
      - "8072:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - condingexam

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: condingexam_php
    volumes:
      - ./src:/var/www
    ports:
      - "9001:9000"
    networks:
      - condingexam

  mysql:
    image: mysql:5.7.29
    command: mysqld --sql_mode=""
    container_name: condingexam_mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: codingexam
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - condingexam
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql

  redis:
    image: redis:4.0
    container_name: condingexam_redis
    ports:
      - "6382:6379"
    networks:
      - condingexam